(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



MapGamma[N_,k_,n_]:=Module[{x,listi,tab1,set1,setf},
tab1={};
listi=comb[N,k];
Do[
set1=listi[[i]];
If[MemberQ[set1,n],
setf=Complement[set1,{n}];
x=c[N,k-1]-Sum[c[N-setf[[p+1]],k-1-p],{p,0,k-2}];
AppendTo[tab1,{i,x}];
];
,{i,1,Length[listi]}];
tab1];

HtGamma[N_,m_,n_]:=Module[{pntr1,Hta,ind1,ind2,coora,ntot1,Htsp,ntot2,inds,
m1,m2,pntr2},
m1=Min[m,N];m2=Min[m-1,N];
(* pointers for start index *)
(*just to be consistent with pther functions styles, insert 0 at 1, otherwise we dont need it here if we modify the lines appropriately *)
pntr1=Insert[Table[Sum[c[N,j],{j,0,i}],{i,0,m1}],0,1];
pntr2=Insert[Table[Sum[c[N,j],{j,0,i}],{i,0,m2}],0,1];
ntot1=pntr1[[-1]];
ntot2=pntr2[[-1]];
(* maps all sectors (up spins); Ht *)
Hta={};
Do[
(* k>0 only *)
inds=MapGamma[N,k,n];
ind1={pntr1[[k+1]]+inds[[;;,1]]}//Transpose;
ind2={pntr1[[k]]+inds[[;;,2]]}//Transpose;
coora=Join[ind1,ind2,2];
AppendTo[Hta,coora ];
,{k,1,m1}];
Htsp=SparseArray[Flatten[Hta,1]-> 1,{ntot1,ntot2}];
Htsp
];

HtKappa[N_,m_]:=Module[{Hta,ntot1,Htsp,ntot2,nsec1,m1,m2},
(* maps all sectors (up spins) at once; 
just remove the max photon sector and shift all the indices *)
m1=Min[m,N];m2=Min[m-1,N];
ntot1=Sum[c[N,j],{j,0,m1}];
ntot2=Sum[c[N,j],{j,0,m2}];
(* map coupled states up to an upper sector det by m2 *)
Hta=Table[{i,i},{i,1,ntot2}];
Htsp=SparseArray[Hta-> 1,{ntot1,ntot2}];
Htsp
];

