(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* :Context: TransOC` *)
(* :Author: Ahsan Zeb, School of Physics and Astronomy, St Andrews, UK*)
(* :Summary: The TransOC package calculates the incoherent charge transport through
			 an organic micorcavity in the strong light-matter coupling regime *)
(* :Copyright: Copyright (c) 2017 Ahsan Zeb, distributed under the XXXX license *)
(* :Package Version: 1.0 *)
(* :Mathematica Version: 10.4.0.0 *)


If[TrueQ[$VersionNumber<10],Print["Sorry, TransOC only works with version 10+ of the Wolfram Language."];Abort[]];


BeginPackage["TransOC`"];


(*auxiliary: *)
$TransOCVersion::usage="$TransOCVersion gives the version number of the TransOC package.";
$TransOCDebugQ::usage="Setting $TransOCDebugQ=True results in debugging messages being printed during evaluations.";


(* function: *)
Trajectory::usage=

"Trajectory runs a Montr Carlo trajectory.

{\!\(\*
StyleBox[\"{\",\nFontSize->18]\)\!\(\*
StyleBox[\"Name\",\nFontSize->18]\)\!\(\*
StyleBox[\",\",\nFontSize->18]\)\!\(\*
StyleBox[\"Default\",\nFontSize->18]\)\!\(\*
StyleBox[\" \",\nFontSize->18]\)\!\(\*
StyleBox[\"value\",\nFontSize->18]\)\!\(\*
StyleBox[\" \",\nFontSize->18]\)\!\(\*
StyleBox[\"(\",\nFontSize->18]\)\!\(\*
StyleBox[\"data\",\nFontSize->18]\)\!\(\*
StyleBox[\" \",\nFontSize->18]\)\!\(\*
StyleBox[\"type\",\nFontSize->18]\)\!\(\*
StyleBox[\")\",\nFontSize->18]\)\!\(\*
StyleBox[\",\",\nFontSize->18]\)\!\(\*
StyleBox[\"Description\",\nFontSize->18]\)\!\(\*
StyleBox[\"}\",\nFontSize->18]\),\[IndentingNewLine]{Ntot,5,Number of molecules in the system},\[IndentingNewLine]{m0,1,number of excitations in the coupled light-matter sub-system},\[IndentingNewLine]{Ds0,{},List of sites that are D at start},\[IndentingNewLine]{Phis0,{},List of sites that are \[Phi]s at start},
{g,1.0,strenght of light-matter coupling for a single molecule,(wR=g.Sqrt[N])},\[IndentingNewLine]{dw,00,Detuning,w0-wc},
{tpar,{0.1,0.001,0.001,0.05,0.1,0.1,0.1,0.1},Hopping parameters,{th,tl,tlh,thl,JhR,JlR,JhL,JlL}},
{Eb,{0.0,0.0},Barriers at the left and right ontacts,Eb={Ebl,Ebr}},\[IndentingNewLine]{kappa,0.005,Cavity losses \[Kappa]},\[IndentingNewLine]{gamma,0.005,Exciton non-radiative decay rate \[Gamma]},\[IndentingNewLine]{Er,0.5,Energy Er due to the applied electric field},\[IndentingNewLine]{w0,2.0,Exciton bare energy Subscript[\[Omega],0]},\[IndentingNewLine]{beta,40.0,\[Beta]=1/Subscript[k,b] T},\[IndentingNewLine]{maxiter,20,Max number of iterations/time steps in the dynamics},\[IndentingNewLine]{includecross,True,Include cross hops,L-H and H-L?},
{BlockInjection,{False,False},Block injection of charge carriers?{BlockLeft,BlockRight}Left contact is cathode,right contact is anodeBlock electron from left and holes from right},
{M,wv,lambda,3,0.2,1.0,Vibrational levels,energy,coupling to electronic statesUsed when VibAssis=True},
{AlwaysLP,True,Quickly relax the quantum system to its lowest eigenstate before an other hop can take place?},
{VibAssis,False,Include vibrational assistance for the Zener tunneling,H-L transitions from active sites H levels?},
{printmem, False, Print memory and some other information},
{fullout, False, full or short output},
{staylow,True, stay in the lowest 2-3 Wr levels, issues when dw =! 0 due to unknown number of states in deg dectors but energetic penalty removes them for 2nd level onwards anyway}\[IndentingNewLine]}

\!\(\*
StyleBox[\"The\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"input\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"argument\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"should\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"be\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"given\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"as\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"Mathematica\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"rules\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"to\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"override\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"the\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"default\",\nFontSize->16]\)\!\(\*
StyleBox[\" \",\nFontSize->16]\)\!\(\*
StyleBox[\"values\",\nFontSize->16]\)\!\(\*
StyleBox[\":\",\nFontSize->16]\)
For example,
out = Trajectory[maxiter -> 100, Ntot \[Rule]  7, m0 -> 5, g \[Rule] 1.5, includecross\[Rule]False];
";


Begin["`Private`"];


$TransOCVersion=1.;
debug:=TrueQ[$TransOCDebugQ];


(* get all .m files from PackageFiles directory *)
Get/@FileNames["*.m",FileNameJoin[{DirectoryName[$InputFileName],"PackageFiles"}]];


End[];
EndPackage[];
